---
language: node_js
node_js:
- '0.8'
- '0.10'
before_script:
- gem update --system
- gem install compass
- gem install breakpoint
- gem install sass-media_query_combiner
- npm install -g grunt-cli
env:
  global:
  - secure: |-
      AJAiEfkWrEX3dm1yyeRE5KSGh/WmGMZNOPlKqu/I+8aoBbLlPTnP0Oevyg7P
      QjiyCUrcScZeIJK4FCdIlbXr9jYDjXWjDlzCOQSmNMJug09LN0r5N96BTRLF
      pB3SvWOC74aK53nMevkEoi7faqnnL7ziJSLUZ9E55N2JxosOUpU=
after_success:
  - chmod -R 777 .travis-build.sh
  - ./travis-build.sh